[package]
name = "babel_monitor"
version = "0.1.0"
authors = ["jkilpatr <jkilpatr@redhat.com>"]

[dependencies]
mockstream = { git = "https://github.com/lazy-bitfield/rust-mockstream.git" }
ascii = "0.9.0"
bufstream = "0.1.3"
ipnetwork = "0.13.0"
failure = "0.1.2"
log = "0.4.3"
env_logger = "0.5.11"
