[package]
name = "bounty_hunter"
version = "0.1.0"
authors = ["kingoflolz <wangben3@gmail.com>"]

[dependencies]
log = "0.4.3"
env_logger = "0.5.11"
num256 = { path = "../num256" }
althea_types = { path = "../althea_types" }
diesel = { version = "1.3.2", features = ["sqlite"] }
dotenv = "0.13.0"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"

[dependencies.rouille]
version = "2.1.0"
default-features = false
