[package]
name = "rita"
version = "0.1.4"
authors = ["Jehan <jehan.tremback@gmail.com>", "Ben <wangben3@gmail.com>"]
build = "build.rs"

[[bin]]
name = "rita_exit"
path = "src/exit.rs"

[[bin]]
name = "rita"
path = "src/client.rs"

[features]
default = []
system_alloc = []

[dependencies]
althea_kernel_interface = { path = "../althea_kernel_interface" }
althea_types = { path = "../althea_types", features = ["actix"]}
babel_monitor = { path = "../babel_monitor" }
clu = { path = "../clu" }
exit_db = { path = "../exit_db" }
num256 = { path = "../num256" }
settings = { path = "../settings" }

actix = { git = "https://github.com/kingoflolz/actix", branch = "althea-mesh"}
actix-web = { git = "https://github.com/actix/actix-web", default-features = false, branch = "fix-missing-content-length"}
actix_derive = "0.3.0"
bytes = "0.4.9"
clippy = { version = "0.0.212", optional = true }
config = "0.9.0"
diesel = { version = "1.3.2", features = ["sqlite"] }
libsqlite3-sys = { version = "0.9.1", features = ["bundled"] }
docopt = "1.0.0"
dotenv = "0.13.0"
env_logger = "0.5.11"
eui48 = {git="https://github.com/althea-mesh/eui48.git"}
failure = "0.1.2"
futures = "0.1.23"
ipnetwork = "0.13.0"
lazy_static = "1.0.2"
lettre = "0.8.2"
lettre_email = "0.8.2"
log = "0.4.3"
minihttpse = "0.1.6"
mockito = "0.12.0"
mockstream = { git = "https://github.com/lazy-bitfield/rust-mockstream.git" }
rand = "0.5.4"
reqwest = "0.8.7"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
tokio = "0.1.7"
tokio-io = "0.1.7"
tokio-codec = "0.1.0"
regex = "1.0.2"
trust-dns-resolver = "0.9.0"
handlebars = "1.0.0"
byteorder = { version = "1.2.4", features = ["i128"] }
