[package]
name = "settings"
version = "0.1.0"
authors = ["Ben <wangben3@gmail.com>"]

[dependencies]
config = "0.9.0"
althea_types = { path = "../althea_types", features = ["actix"]}
althea_kernel_interface = { path = "../althea_kernel_interface" }
eui48 = {git="https://github.com/althea-mesh/eui48.git"}
num256 = { path = "../num256" }
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
toml = "0.4.6"
log = "0.4.3"
failure = "0.1.2"
owning_ref = {git="https://github.com/kingoflolz/owning-ref-rs/", branch="fix-bug"}
lazy_static = "1.0.2"
